### ISSUE TITLE
CLIs do not work anymore

### ISSUE THREAD

**Issue by bertsky** [mjenckel/ocrd_anybaseocr#10]
This is what I get on the current version after `make install` from a `ocrd-anybaseocr-crop --help`:
```
Traceback (most recent call last):
  File "env3/bin/ocrd-anybaseocr-crop", line 6, in <module>
    from ocrd_anybaseocr.cli.cli import ocrd_anybaseocr_cropping
  File "env3/lib/python3.6/site-packages/ocrd_anybaseocr/cli/cli.py", line 4, in <module>
    from ocrd_anybaseocr.cli.ocrd_anybaseocr_binarize import OcrdAnybaseocrBinarizer
  File "env3/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_binarize.py", line 49, in <module>
    from ..utils import print_info, print_error
ModuleNotFoundError: No module named 'ocrd_anybaseocr.utils'
```

**Comment by mjenckel** [comment]
removed an old unnecessary file but missed to remove all links to it
should be fixed

**Comment by bertsky** [comment]
Thanks – that did help!
