### ISSUE TITLE
Problem with torch

### ISSUE THREAD

**Issue by kba** [mjenckel/ocrd_anybaseocr#24]
```
ocrd-anybaseocr-crop --help
Traceback (most recent call last):
  File "/data/monorepo/venv3.6/bin/ocrd-anybaseocr-crop", line 11, in <module>
    load_entry_point('ocrd-anybaseocr', 'console_scripts', 'ocrd-anybaseocr-crop')()
  File "/data/monorepo/venv3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/monorepo/venv3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/data/monorepo/venv3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/data/monorepo/venv3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/monorepo/LAYoutERkennung/ocrd_anybaseocr/cli/cli.py", line 7, in <module>
    from ocrd_anybaseocr.cli.ocrd_anybaseocr_dewarp import OcrdAnybaseocrDewarper
  File "/data/monorepo/LAYoutERkennung/ocrd_anybaseocr/cli/ocrd_anybaseocr_dewarp.py", line 1, in <module>
    import torch
  File "/data/monorepo/venv3.6/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS
```

Have you encountered that and any idea how to fix it?

```sh
$ cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
```

**Comment by bertsky** [comment]
https://github.com/pytorch/pytorch/issues/2575 suggests that your OS is too old: it contains a glibc bug that causes this. (But some people have got it working nevertheless, by changing import order. Since the only processor in here which does use Torch is dewarping, I don't think this will help you, though.)

**Comment by kba** [comment]
Yeah, I tried fiddling with import order and `LD_PRELOAD` to no avail. I'm just confused why this didn't happen in the past. I'm now trying to circumvent this by using it inside a docker container...

**Comment by kba** [comment]
Running a docker container built from master of our fork works.
