### ISSUE TITLE
"UnboundLocalError" in block segmentation

### ISSUE THREAD

**Issue by wrznr** [mjenckel/ocrd_anybaseocr#37]
Pls. help:
```
$ ocrd-anybaseocr-block-segmentation -I ORIGINAL -O DFKIBS,DFKIBS-IMG -m mets.xml -p '{"block_segmentation_model" : "/home/kmw/Documents/Work/OCR-D/models/DFKI", "block_segmentation_weights" : "/home/kmw/Documents/Work/OCR-D/models/DFKI/block_segmentation_weights.h5"}'
2020-01-22 13:06:40.432457: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-01-22 13:06:40.435024: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Using TensorFlow backend.
13:06:41.043 WARNING tensorflow - From /home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/tensorflow_core/python/compat/v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
13:06:41.172 INFO ocrd.workspace_validator - input_file_grp=['ORIGINAL'] output_file_grp=['DFKIBS', 'DFKIBS-IMG']
['ORIGINAL']
13:06:41.181 WARNING tensorflow - From /home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_block_segmentation.py:68: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
13:06:44.158 WARNING tensorflow - From /home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
13:06:46.405 WARNING tensorflow - From /home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/model.py:427: calling crop_and_resize_v1 (from tensorflow.python.ops.image_ops_impl) with box_ind is deprecated and will be removed in a future version.
Instructions for updating:
box_ind is deprecated, use box_indices instead
13:06:46.671 WARNING tensorflow - From /home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/model.py:776: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
Processing 1 images
image                    shape: (2754, 2044, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  136.20000  float64
image_metas              shape: (1, 27)               min:    0.00000  max: 2754.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32
Traceback (most recent call last):
  File "/home/kmw/Documents/Work/OCR-D/dbg-env/bin/ocrd-anybaseocr-block-segmentation", line 11, in <module>
    load_entry_point('ocrd-anybaseocr==0.0.1', 'console_scripts', 'ocrd-anybaseocr-block-segmentation')()
  File "/home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/ocrd_anybaseocr/cli/cli.py", line 54, in ocrd_anybaseocr_block_segmentation
    return ocrd_cli_wrap_processor(OcrdAnybaseocrBlockSegmenter, *args, **kwargs)
  File "/home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/ocrd/decorators.py", line 60, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/ocrd/processor/base.py", line 57, in run_processor
    processor.process()
  File "/home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_block_segmentation.py", line 110, in process
    self._process_segment(page_image, page, page_xywh, page_id, input_file, n, mrcnn_model, class_names)
  File "/home/kmw/Documents/Work/OCR-D/dbg-env/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_block_segmentation.py", line 193, in _process_segment
    if border:
UnboundLocalError: local variable 'border' referenced before assignment
```

**Comment by wrznr** [comment]
Your code cannot work for pages without a border. Impossible. Is this documented?

**Comment by mahmed1995** [comment]
Should be working now. Fixed in da7e62e

**Comment by mahmed1995** [comment]
@wrznr Can this be closed now?

**Comment by wrznr** [comment]
LGTM
