### ISSUE TITLE
No module named 'ocrd_anybaseocr.pix2pixhd'

### ISSUE THREAD

**Issue by ghost** [mjenckel/ocrd_anybaseocr#64]
```
(d2) home@home-lnx:~/programs/ocrd_anybaseocr$ ocrd-anybaseocr-dewarp -m ./data/mets.xml -I OCR-D-PAGE-CROP -O OCR-D-PAGE-DEWARP -p ./dewarp/latest_net_G.pth
Traceback (most recent call last):
  File "/home/home/anaconda3/envs/d2/bin/ocrd-anybaseocr-dewarp", line 5, in <module>
    from ocrd_anybaseocr.cli.ocrd_anybaseocr_dewarp import cli
  File "/home/home/anaconda3/envs/d2/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_dewarp.py", line 29, in <module>
    from ..pix2pixhd.options.test_options import TestOptions
ModuleNotFoundError: No module named 'ocrd_anybaseocr.pix2pixhd'
```

the commands i used to install ocrd_anybaseocr:
```
git clone https://github.com/OCR-D/ocrd_anybaseocr.git
git submodule update --init
make install
```

**Comment by kba** [comment]
Run `make patch-pix2pixhd` before `make install`. Documentation needs to be updated.

**Comment by ghost** [comment]
@kba Nope, still not working
Here is a step-by-step commands:

```
git clone https://github.com/OCR-D/ocrd_anybaseocr.git
cd ocrd_anybaseocr
git submodule update --init
make patch-pix2pixhd
make install
mkdir ./models
wget -O ./models/latest_net_G.pth https://cloud.dfki.de/owncloud/index.php/s/3zKza5sRfQB3ygy/download
wget https://ocr-d-repo.scc.kit.edu/api/v1/dataresources/16568d42-57be-4367-a335-4687bc84953e/data/weigel_gnothi02_1618.ocrd.zip
unzip weigel_gnothi02_1618.ocrd.zip 'data/*' -d ./
ocrd-anybaseocr-binarize -m ./data/mets.xml -I OCR-D-IMG -O OCR-D-PAGE-BIN
ocrd-anybaseocr-deskew -m ./data/mets.xml -I OCR-D-PAGE-BIN -O OCR-D-PAGE-DESKEW
ocrd-anybaseocr-crop -m ./data/mets.xml -I OCR-D-PAGE-DESKEW -O OCR-D-PAGE-CROP
CUDA_VISIBLE_DEVICES=0 ocrd-anybaseocr-dewarp -m ./data/mets.xml -I OCR-D-PAGE-CROP -O OCR-D-PAGE-DEWARP -p ./models/latest_net_G.pth

```

Resulting in error:
```
Traceback (most recent call last):
  File "/home/home/anaconda3/envs/ocrd/bin/ocrd-anybaseocr-dewarp", line 5, in <module>
    from ocrd_anybaseocr.cli.ocrd_anybaseocr_dewarp import cli
  File "/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_dewarp.py", line 29, in <module>
    from ..pix2pixhd.options.test_options import TestOptions
ModuleNotFoundError: No module named 'ocrd_anybaseocr.pix2pixhd'
```

**Comment by kba** [comment]
Can you post output of

```
find /home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr
```

please?

**Comment by ghost** [comment]
```
(ocrd) home@home-lnx:~/programs/ocrd_anybaseocr$ find /home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_textline.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_layout_analysis.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/__init__.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_deskew.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_block_segmentation.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_cropping.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/__pycache__
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/__pycache__/ocrd_anybaseocr_binarize.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/__pycache__/__init__.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/__pycache__/ocrd_anybaseocr_block_segmentation.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/__pycache__/ocrd_anybaseocr_deskew.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/__pycache__/ocrd_anybaseocr_dewarp.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/__pycache__/ocrd_anybaseocr_tiseg.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/__pycache__/ocrd_anybaseocr_cropping.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/__pycache__/ocrd_anybaseocr_layout_analysis.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/__pycache__/ocrd_anybaseocr_textline.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_tiseg.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_binarize.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_dewarp.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/params.json
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/model.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/__init__.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/config.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/parallel_model.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/utils.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/__pycache__
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/__pycache__/__init__.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/__pycache__/utils.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/__pycache__/model.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/__pycache__/parallel_model.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/mrcnn/__pycache__/config.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/constants.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/__init__.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/ocrd-tool.json
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/tensorflow_importer.py
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/__pycache__
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/__pycache__/__init__.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/__pycache__/tensorflow_importer.cpython-36.pyc
/home/home/anaconda3/envs/ocrd/lib/python3.6/site-packages/ocrd_anybaseocr/__pycache__/constants.cpython-36.pyc
```

**Comment by kba** [comment]
OK, so apparently `ocrd_anybaseocr/pix2pixhd` is not installed. I'll try to reproduce.

**Comment by ghost** [comment]
yup

**Comment by ghost** [comment]
.

**Comment by kba** [comment]
> .

What's your point? :)

**Comment by deepseek** [comment]
that was just as a reminder,
though i still am not able to run this project.
i have more than 20,000,000 document images with layout annotations, and i want to see if this project is worth investing in.

**Comment by ghost** [comment]
hmmm... interesting,
why did you reopen?

**Comment by kba** [comment]
Problem still unsolved, just haven't gotten around to investigate.
