### ISSUE TITLE
test_A dir in dewarping

### ISSUE THREAD

**Issue by EEngl52** [mjenckel/ocrd_anybaseocr#77]
if `ocrd-anybaseocr-dewarp` doesn't run through successfully and you call it again in the same workspace with `--overwrite`, it gives you the following error message referring to a `test_A` which was created in `-I`:

```
---------- Networks initialized -------------
model [Pix2PixHDModel] was created
15:18:17.802 INFO OcrdAnybaseocrDewarper - INPUT FILE P_bsb00013141_00012
15:18:17.869 ERROR ocrd.workspace.image_from_page - page "P_bsb00013141_00012" image (,cropped,binarized,despeckled,deskewed; 1092x1787) has not been cropped properly (1090x1787)
Traceback (most recent call last):
  File "/home/habocr/ocrd_all/venv/local/sub-venv/headless-tf21/bin/ocrd-anybaseocr-dewarp", line 8, in <module>
    sys.exit(cli())
  File "/home/habocr/ocrd_all/venv/local/sub-venv/headless-tf21/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/habocr/ocrd_all/venv/local/sub-venv/headless-tf21/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/habocr/ocrd_all/venv/local/sub-venv/headless-tf21/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/habocr/ocrd_all/venv/local/sub-venv/headless-tf21/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/habocr/ocrd_all/venv/local/sub-venv/headless-tf21/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_dewarp.py", line 190, in cli
    return ocrd_cli_wrap_processor(OcrdAnybaseocrDewarper, *args, **kwargs)
  File "/home/habocr/ocrd_all/venv/local/sub-venv/headless-tf21/lib/python3.6/site-packages/ocrd/decorators/__init__.py", line 81, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/home/habocr/ocrd_all/venv/local/sub-venv/headless-tf21/lib/python3.6/site-packages/ocrd/processor/helpers.py", line 70, in run_processor
    processor.process()
  File "/home/habocr/ocrd_all/venv/local/sub-venv/headless-tf21/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_dewarp.py", line 137, in process
    dataset = prepare_data(opt, page_image)
  File "/home/habocr/ocrd_all/venv/local/sub-venv/headless-tf21/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_dewarp.py", line 39, in prepare_data
    Path(opt.dataroot, 'test_A').mkdir()
  File "/usr/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileExistsError: [Errno 17] File exists: '/test/data/workflows/OCR-D-BIN-DENOISE-DESKEW/test_A'
```

**Comment by kba** [comment]
fixed by #89
